package zane.way.test;

import com.github.zaneway.bc.csr.CsrResponse;
import com.github.zaneway.bc.sm2.SM2EnvelopedKey;
import java.util.Base64;
import java.util.List;
import org.bouncycastle.asn1.x509.Certificate;
import org.bouncycastle.util.encoders.Hex;

public class CsrBuilder {

  public static void main(String[] args) throws Exception {
    String csr = "MIIFrTGCAiYwggIiMIIBxqADAgECAghCLv+A558CjDAMBggqgRzPVQGDdQUAMCMxCzAJBgNVBAYTAkNOMRQwEgYDVQQDDAvlrZBDQeivgeS5pjAeFw0yNDA4MTcxNjAwMDBaFw0yOTA4MTYxNjAwMDBaMFwxFDASBgNVBAMMC0NvbW1vbiBOYW1lMRMwEQYDVQQIDApTdGF0ZSBOYW1lMRQwEgYDVQQKDAtPcmduaXphdGlvbjEZMBcGA1UECwwQT3Jnbml6YXRpb24gVW5pdDBZMBMGByqGSM49AgEGCCqBHM9VAYItA0IABEqaM/EOfuRIXFZEMRzDrvwkFw9Kr3+SHPq33/CtbF0NbBfHjkGRV9KNPJXhVUDaf1qlEjaBIWjxNS+KvaQXwY+jgagwgaUwHwYDVR0jBBgwFoAUPkeQoaB88khQP5VxZNXtr8gXKewwDAYDVR0TBAUwAwEBADBFBgNVHSUEPjA8BggrBgEFBQcDAQYIKwYBBQUHAwIGCCsGAQUFBwMDBggrBgEFBQcDBAYIKwYBBQUHAwgGCCsGAQUFBwMJMA4GA1UdDwEB/wQEAwIGwDAdBgNVHQ4EFgQU5410car9iRZfU2dmslH71U+BvuEwDAYIKoEcz1UBg3UFAANIADBFAiBlQpqRQJl9u2L4Ax+yYDxmkVv3ryas7B8wKMoKizf9ugIhAKks6TJIK8mRAvXGqmwem2Q41Gd6uRr4+FX+//PnheKuoIIBUjCCAU4wCQYHKoEcz1UBaDB5AiAWuHEisiIR6n9zLl7jhH0X2EKVtk2mUiYDUNIop7CNhwIhAJnoEUXOi2ejNyRsLUegJJLI8Q6/Avad7tX6xQcfAffDBCAddZRgCgL0uGvxItMjRPiD8ateBGS6aBx5OGDgep3yRwQQssKusWuTyK+Wvva+dTfflwNCAASgM748lDZqIjexXRncRWXgXBslk45kzEnEmQ7Oc2I1vTWaVZDbfPQSGcu/vepj7KcCZE53aX02zBXPapUi0H9SA4GBAPo4yA8IFdvzxifrweTOs0tuedxWp5nHFHrt2UGnpMf8w3NccTPK6zajLWPIffUxfVVapeqlA9TO35Xc7t2FV+9bN8mBfJoH/6yGEVntWKm/zXqj606oJK8wciSTygpjb2aTPN8fHEhQ9HePnMlouwOz0Ri0184HI6af8kbXNxJKoYICKTGCAiUwggIhMIIBxqADAgECAghemiogoH6Y1TAMBggqgRzPVQGDdQUAMCMxCzAJBgNVBAYTAkNOMRQwEgYDVQQDDAvlrZBDQeivgeS5pjAeFw0yNDA4MTcxNjAwMDBaFw0yOTA4MTYxNjAwMDBaMFwxFDASBgNVBAMMC0NvbW1vbiBOYW1lMRMwEQYDVQQIDApTdGF0ZSBOYW1lMRQwEgYDVQQKDAtPcmduaXphdGlvbjEZMBcGA1UECwwQT3Jnbml6YXRpb24gVW5pdDBZMBMGByqGSM49AgEGCCqBHM9VAYItA0IABKAzvjyUNmoiN7FdGdxFZeBcGyWTjmTMScSZDs5zYjW9NZpVkNt89BIZy7+96mPspwJkTndpfTbMFc9qlSLQf1KjgagwgaUwHwYDVR0jBBgwFoAUPkeQoaB88khQP5VxZNXtr8gXKewwDAYDVR0TBAUwAwEBADBFBgNVHSUEPjA8BggrBgEFBQcDAQYIKwYBBQUHAwIGCCsGAQUFBwMDBggrBgEFBQcDBAYIKwYBBQUHAwgGCCsGAQUFBwMJMA4GA1UdDwEB/wQEAwIDODAdBgNVHQ4EFgQUBneYuS56E/57fJ2DC1g8hH9CyiIwDAYIKoEcz1UBg3UFAANHADBEAiBcD5x0m//xB6PRzE2UHo2jkGFoaXdAQqdkT76AoEDbhgIgTuVb2ZyOshOASlwsRgCFAk9mVTXBJ/NhHlMZ9PNPBr4=";
    CsrResponse response = CsrResponse.getInstance(Base64.getDecoder().decode(csr));
    System.out.println(Base64.getEncoder().encodeToString(response.getEncoded()));
    List<Certificate> certificateSet = response.getCertificateSet();
    for (Certificate certificate : certificateSet) {
      System.out.println(certificate.getSubject().toString());
    }
    SM2EnvelopedKey sm2EnvelopedKey = response.getSm2EnvelopedKey();
    System.out.println(Hex.toHexString(sm2EnvelopedKey.getSm2PublicKey().getOctets()));

  }



}
